# basic settings
title: "Minho's Blog"
email: "mino@inha.edu"
description: "Spatial AI and Robotics"
author: "Minho Lee"
baseurl: ""
url: "https://roboxiv.com"
date_format: "%b %d, %Y"

# paginations & permalinks
paginate: 4
paginate_path: "/page:num/"
permalink: pretty

# disqus comments
# disqus_comments: "yes"
# disqus_shortname: "iminolee"

# utterances comments
utterances_comments: "yes"
utterances_repo: "iminolee/iminolee.github.io"

# formsubmit.io
formsubmit_email: "mino@inha.edu"

# google maps
# google_maps_api_key: "" #google maps api key
# google_maps_lat: "" #google maps latitude
# google_maps_long: "" #google maps longitude
# google_maps_zoom: "14" #google maps zoom

# collections
collections:
  - works

# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

sass:
  style: compressed

markdown: kramdown

toc:
  min_level: 1
  max_level: 5